print("            .-/+oossssssoo+/-.")
print("        `:+ssssssssssssssssssss+:`")
print("     -+ssssssssssssssssssssyyssss+-")
print("    .ossssssssssssssssssssdMMMNysssso.")
print("   /sssssssssssshdmmNNmmyNMMMMhsssssss\\")
print("  +sssssssssshmydMMMMMMMNddddysssssssss+")
print(" /ssssssssshNMMyhhyyyyhmNMMMNhssssssssss\\")
print(".sssssssssdMMMNhsssssssssshNMMMMdssssssss.")
print("+ssssshhhyNMMNysssssssssssssyNMMMMyssssss+")
print("osssyNMMMNyMMhssssssssssssssshmmmhssssssso")
print("osssyNMMMNyMMhssssssssssssssshmmmhssssssso")
print("+ssssshhhyNMMNysssssssssssssyNMMMMyssssss+")
print(".sssssssssdMMMNhsssssssssshNMMMMdssssssss.")
print(" \\ssssssssshNMMyhhyyyyhmNMMMNhssssssssss/")
print("  +sssssssssshmydMMMMMMMNddddysssssssss+")
print("   \\sssssssssssshdmmNNmmyNMMMMhsssssss/")
print("    .osssssssssssssssssssdMMMNyssssso.")
print("     -+sssssssssssssssssssyysssss+-")
print("        `:+ssssssssssssssssssss+:`")
print("            .-/+oossssssoo+/-.")
